### ISSUE TITLE
Android Test Failures

### ISSUE THREAD

**Issue by kitsonk** [dojo/dom#41]
Now that I have everything merged and updated (as well as moved over to SauceLabs for testing), there are some additional failures on [Android 4.4](https://travis-ci.org/dojo/dom/builds/122197354#L452):

```
× android 4.4 on Linux - unit tests - addCssRule - addCssRule - add rule - multiple properties (0.005s)
AssertionError: expected '8px' to equal '4px'
  at Assertion.assertEqual  <__intern/browser_modules/chai/chai.js:776:12>
  at Assertion.ctx.(anonymous function) [as equal]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Function.assert.strictEqual  <__intern/browser_modules/chai/chai.js:2329:32>
  at Test.registerSuite.addCssRule.add rule.multiple properties [as test]  <tests/unit/addCssRule.ts:46:12>
  at <__intern/lib/Test.js:181:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
× android 4.4 on Linux - unit tests - addCssRule - addCssRule - add multiple rules (0.001s)
AssertionError: expected '8px' to equal '4px'
  at Assertion.assertEqual  <__intern/browser_modules/chai/chai.js:776:12>
  at Assertion.ctx.(anonymous function) [as equal]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Function.assert.strictEqual  <__intern/browser_modules/chai/chai.js:2329:32>
  at Test.registerSuite.addCssRule.add multiple rules [as test]  <tests/unit/addCssRule.ts:57:11>
  at <__intern/lib/Test.js:181:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
× android 4.4 on Linux - unit tests - addCssRule - addCssRule - #destroy - destroy out of order (0.002s)
AssertionError: expected '8px' to equal '6px'
  at Assertion.assertEqual  <__intern/browser_modules/chai/chai.js:776:12>
  at Assertion.ctx.(anonymous function) [as equal]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Function.assert.strictEqual  <__intern/browser_modules/chai/chai.js:2329:32>
  at Test.registerSuite.addCssRule.#destroy.destroy out of order [as test]  <tests/unit/addCssRule.ts:111:12>
  at <__intern/lib/Test.js:181:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
× android 4.4 on Linux - unit tests - addCssRule - addCssRule - #set - single (0.001s)
AssertionError: expected '8px' to equal '4px'
  at Assertion.assertEqual  <__intern/browser_modules/chai/chai.js:776:12>
  at Assertion.ctx.(anonymous function) [as equal]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Function.assert.strictEqual  <__intern/browser_modules/chai/chai.js:2329:32>
  at Test.registerSuite.addCssRule.#set.single [as test]  <tests/unit/addCssRule.ts:150:12>
  at <__intern/lib/Test.js:181:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
× android 4.4 on Linux - unit tests - addCssRule - addCssRule - #set - multiple (0.002s)
AssertionError: expected '8px' to equal '4px'
  at Assertion.assertEqual  <__intern/browser_modules/chai/chai.js:776:12>
  at Assertion.ctx.(anonymous function) [as equal]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Function.assert.strictEqual  <__intern/browser_modules/chai/chai.js:2329:32>
  at Test.registerSuite.addCssRule.#set.multiple [as test]  <tests/unit/addCssRule.ts:163:12>
  at <__intern/lib/Test.js:181:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
>> android 4.4 on Linux: 5/129 tests failed
```

**Comment by vansimke** [comment]
I've looked into this a bit, and it seems like something specific to the font-size property for Android 4.4 on Sauce Labs. This doesn't repeat on a local VM or on Browserstack. It also doesn't happen on other CSS properties. Based on that, I'm thinking about switching over to another CSS property such as fill. It should still test the same goals as font-size, but will work around the apparent bug.
